version: "3.9"
services:
  db:
    image: postgres:16
    container_name: meteorite-qna-pg
    environment:
      POSTGRES_USER: meteorite-user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: meteorites
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  dbdata: